version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  processor:
    build:
      context: .
      dockerfile: cmd/processor/Dockerfile
    depends_on:
      - rabbitmq
      - postgres

  nickfury:
    build:
      context: .
      dockerfile: script/Dockerfile
    depends_on:
      - api

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bank
