name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./script  

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install deps
        run: go mod tidy

      - name: Run tests
        run: make test || go test ./...  

      - name: Lint
        run: go vet ./...

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        working-directory: ./script   # 👈 Dockerfile dentro de script
        run: docker build -t statement-app .
