name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: statement
        ports:
          - 5432:5432

      redis:
        image: redis:7
        ports:
          - 6379:6379

      # kafka:
      #   image: bitnami/kafka:3
      #   ports:
      #     - 9092:9092
      # 👉 descomentar quando implementar mensageria no Ironman/Thor

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      # -----------------------------------------------------
      # 👉 Build Orquestrador (Avengers)
      # working-directory: ./avengers
      # run: go build -o ../../orchestrator ./cmd/api/main.go
      #
      # - name: Run Orchestrator in background
      #   run: |
      #     ./orchestrator &
      #     sleep 5
      #     curl -f http://localhost:8080/health || exit 1
      #
      # -----------------------------------------------------
      # (deixa comentado até o Orquestrador estar implementado)

      - name: Run validation script
        working-directory: ./script
        run: go run main.go --test
        # ⚠️ Este comando vai falhar se o Orquestrador não existir.
        # Deixe comentado até implementar os endpoints.
        # run: go run main.go --test

      - name: Lint
        run: go vet ./...
